name: PR Agent with OpenRouter

on:
  pull_request:
    types: [opened, reopened, ready_for_review, review_requested, synchronize]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    # Evita loops com bots
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent on every pull request

    steps:
      - name: PR Agent action step
        id: pragent
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENROUTER__KEY: ${{ secrets.OPENROUTER_API_KEY }}
